/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as PayIndexRouteImport } from './routes/pay/index'
import { Route as PaySlugRouteImport } from './routes/pay/$slug'
import { Route as TCodeRouteImport } from './routes/t/$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api/mpesa/callback'
import { Route as AppFloorIndexRouteImport } from './routes/app/floor/index'
import { Route as AppFloorLocationIdRouteImport } from './routes/app/floor/$locationId'
import { Route as ApiHardwareTablesIdRouteImport } from './routes/api/hardware/tables/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const PayIndexRoute = PayIndexRouteImport.update({
  id: '/pay/',
  path: '/pay/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa/callback',
  path: '/api/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFloorIndexRoute = AppFloorIndexRouteImport.update({
  id: '/floor/',
  path: '/floor/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFloorLocationIdRoute = AppFloorLocationIdRouteImport.update({
  id: '/floor/$locationId',
  path: '/floor/$locationId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiHardwareTablesIdRoute = ApiHardwareTablesIdRouteImport.update({
  id: '/api/hardware/tables/$id',
  path: '/api/hardware/tables/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/t/$code': typeof TCodeRoute
  '/app/': typeof AppIndexRoute
  '/pay/': typeof PayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/app/floor/$locationId': typeof AppFloorLocationIdRoute
  '/app/floor/': typeof AppFloorIndexRoute
  '/api/hardware/tables/$id': typeof ApiHardwareTablesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/t/$code': typeof TCodeRoute
  '/app': typeof AppIndexRoute
  '/pay': typeof PayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/app/floor/$locationId': typeof AppFloorLocationIdRoute
  '/app/floor': typeof AppFloorIndexRoute
  '/api/hardware/tables/$id': typeof ApiHardwareTablesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/t/$code': typeof TCodeRoute
  '/app/': typeof AppIndexRoute
  '/pay/': typeof PayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/app/floor/$locationId': typeof AppFloorLocationIdRoute
  '/app/floor/': typeof AppFloorIndexRoute
  '/api/hardware/tables/$id': typeof ApiHardwareTablesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/alerts'
    | '/app/reports'
    | '/app/settings'
    | '/app/transactions'
    | '/pay/$slug'
    | '/t/$code'
    | '/app/'
    | '/pay/'
    | '/api/auth/$'
    | '/api/mpesa/callback'
    | '/app/floor/$locationId'
    | '/app/floor/'
    | '/api/hardware/tables/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/alerts'
    | '/app/reports'
    | '/app/settings'
    | '/app/transactions'
    | '/pay/$slug'
    | '/t/$code'
    | '/app'
    | '/pay'
    | '/api/auth/$'
    | '/api/mpesa/callback'
    | '/app/floor/$locationId'
    | '/app/floor'
    | '/api/hardware/tables/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/alerts'
    | '/app/reports'
    | '/app/settings'
    | '/app/transactions'
    | '/pay/$slug'
    | '/t/$code'
    | '/app/'
    | '/pay/'
    | '/api/auth/$'
    | '/api/mpesa/callback'
    | '/app/floor/$locationId'
    | '/app/floor/'
    | '/api/hardware/tables/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaySlugRoute: typeof PaySlugRoute
  TCodeRoute: typeof TCodeRoute
  PayIndexRoute: typeof PayIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiHardwareTablesIdRoute: typeof ApiHardwareTablesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/pay/': {
      id: '/pay/'
      path: '/pay'
      fullPath: '/pay/'
      preLoaderRoute: typeof PayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/callback': {
      id: '/api/mpesa/callback'
      path: '/api/mpesa/callback'
      fullPath: '/api/mpesa/callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/floor/': {
      id: '/app/floor/'
      path: '/floor'
      fullPath: '/app/floor/'
      preLoaderRoute: typeof AppFloorIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/floor/$locationId': {
      id: '/app/floor/$locationId'
      path: '/floor/$locationId'
      fullPath: '/app/floor/$locationId'
      preLoaderRoute: typeof AppFloorLocationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/hardware/tables/$id': {
      id: '/api/hardware/tables/$id'
      path: '/api/hardware/tables/$id'
      fullPath: '/api/hardware/tables/$id'
      preLoaderRoute: typeof ApiHardwareTablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFloorLocationIdRoute: typeof AppFloorLocationIdRoute
  AppFloorIndexRoute: typeof AppFloorIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppFloorLocationIdRoute: AppFloorLocationIdRoute,
  AppFloorIndexRoute: AppFloorIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PaySlugRoute: PaySlugRoute,
  TCodeRoute: TCodeRoute,
  PayIndexRoute: PayIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiHardwareTablesIdRoute: ApiHardwareTablesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
